# Generated by Django 4.2.1 on 2023-07-28 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('captain', models.CharField(max_length=100, verbose_name='Captain')),
                ('regDate', models.DateField(default=datetime.datetime.now, verbose_name='regDate')),
                ('duration', models.IntegerField(default=30, verbose_name='Duration')),
                ('expDate', models.DateField(verbose_name='expDate')),
                ('paid', models.IntegerField(default=0, verbose_name='Paid')),
                ('isActive', models.BooleanField(default=False, verbose_name='isActive')),
            ],
        ),
    ]
