# Generated by Django 4.2.1 on 2023-07-30 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expDate',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 16, 40, 42, 365432), verbose_name='expDate'),
        ),
    ]
