# Generated by Django 4.2.1 on 2023-07-31 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csite', '0002_alter_member_expdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='paymentCount',
            field=models.IntegerField(default=0, verbose_name='paymentCount'),
        ),
        migrations.AlterField(
            model_name='member',
            name='expDate',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 20, 37, 54, 288578), verbose_name='expDate'),
        ),
        migrations.AlterField(
            model_name='member',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='isActive'),
        ),
    ]
