# Generated by Django 4.2.1 on 2023-08-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csite', '0008_alter_member_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expDate',
            field=models.DateField(default='01-01-2001', verbose_name='expDate'),
        ),
    ]
