# Generated by Django 4.2.1 on 2023-08-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csite', '0009_alter_member_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expDate',
            field=models.DateField(default='2001-01-01', verbose_name='expDate'),
        ),
    ]
