# Generated by Django 4.2.1 on 2023-08-17 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csite', '0010_alter_member_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='expDate'),
        ),
    ]
